blueprint:
  name: Paralelo Virtual RFL
  description: Acenda/Apaga todos os switchs/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
        entity:
          domain:
            - switch
            - light
          multiple: true

trigger:
  platform: state
  entity_id: !input entrada_switchs

condition:
  - condition: template
    value_template: >
      {% if trigger.to_state.state == "on" %}
        {{ trigger.from_state is not none and trigger.from_state.state != 'on' }}
      {% elif trigger.to_state.state == "off" %}
        {{ trigger.from_state is not none and trigger.from_state.state != 'off' }}
      {% else %}
        false
      {% endif %}

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id: !input entrada_switchs
  - delay:
      seconds: 1

mode: single
